.catalog:
  name: "MongoShardedClusterServer"
  version: "3.2-rancher1"
  description: "MongoDB Sharded Cluster"
  uuid: mongodb-1
  minimum_rancher_version: v0.46.0
  questions:    
    - variable: config_repl_set_name
      description: "Name of the Config MongoDB replicaSet"
      label: "Config ReplicaSet Name"
      type: "string"
      required: true
      default: "configReplSet"  
    - variable: repl_set_prefix
      description: "Prefix for the MongoDB replicaSet"
      label: "ReplicaSet Prefix Name"
      type: "string"
      required: true
      default: "rs"
mongo-s:
  scale: 2
mongo-shard-one:
  scale: 3
mongo-shard-two:
  scale: 3
mongo-config:
  scale: 3
  retain_ip: true
  metadata:
    mongo:
      yml:
        replset.name: "${replset_name}"

