mongo-config:
  restart: always
  environment:
    MONGO_SERVICE_NAME: mongo-config
  tty: true
  entrypoint: /opt/rancher/bin/entrypoint.sh
  command:
  - --configsvr  
  - --port 27017
  - --replSet
  - "${config_repl_set_name}"
  image: mongo:3.2
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: mongo-base, mongo-datavolume
    io.rancher.container.network: true
  volumes_from:
    - mongo-datavolume
    - mongo-base
mongo-s:
  restart: always
  environment:
    MONGO_SERVICE_NAME: mongo-s
  tty: true
  entrypoint: mongos --configdb ${config_repl_set_name}/mongo-config:27017
  image: mongo:3.2
  labels:
    io.rancher.container.network: true
  links: 
     - mongo-config
mongo-base:
  restart: always
  net: none
  tty: true
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
  image: rancher/mongodb-conf:v0.1.0
  stdin_open: true
  entrypoint: /bin/true
mongo-datavolume:
  net: none
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
  volumes:
    - /data/db
  entrypoint: /bin/true
  image: busybox

