.catalog:
  name: "MongoConfigServer"
  version: "3.2-rancher1"
  description: "MongoDB Config Server"
  uuid: mongodb-1
  minimum_rancher_version: v0.46.0
  questions:
    - variable: replset_name
      description: "Name of the MongoDB replicaSet"
      label: "Config ReplicaSet Name"
      type: "string"
      required: true
      default: "configReplSet"
mongo-config:
  scale: 3
  retain_ip: true
  metadata:
    mongo:
      yml:
        replset.name: "${replset_name}"

